### ISSUE TITLE
Prevent reconciliation of machines with invalid credentials

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1148]
/kind bug

A 'fat finger' bug we have seen more than once in the wild now involves the user accidentally updating cloud credentials with *valid* credentials for the *wrong cloud*. In at least one case it was a staging environment. In another case the credentials referred to the wrong region.

In both cases we ended up marking the Machines as failed because the cloud we connected to reported that the underlying resources don't exist.

While this is user error, the user impact is significant (all machines become failed) and there should be some way for us to detect it. I propose adding metadata to `OpenStackMachine.Status` which uniquely and unambiguously identifies the cloud the Machine was originally created in. If they don't match we would refuse to reconcile the machine at all, but not mark it failed.

I believe project id would be a good fit for this, although it may need to be combined with region.

Proposed for 0.6: #1145

**Comment by jichenjc** [comment]
I guess it's a requirement instead of a bug since it's because user invalid input and CAPO just take actions according and I agree we should fix it nevertheless 

I think the issue you reported is 
1) we create cloud.conf and create cluster then everything fine
2) the cloud.conf got updated due to any reason but `wrong` configuration input 
3) then next reconcile makes the compute resource become fail

`OpenStackMachine.Status` should be able to identify the machine, what about other resources e.g sec group , LB etc? will that be impacted? how about some staus recorded in cluster level so we can compare this at high level instead ?
