### ISSUE TITLE
Think about using OpenStack Server Groups

### ISSUE THREAD

**Issue by chrigl** [kubernetes-sigs/cluster-api-provider-openstack#118]
Currently, when the machine actuator creates VMs, it goes to OpenStack Compute and asks for a VM, for the next VM, again, and again and again. This might result in having all VMs on a single hypervisor.

Well. OpenStack provides a way to configure anti-affinity. See https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/server-group.html.

For sure, this does not come without problems. As long as there are hypervisor without "our"-VMs running on, everything is fine. But if "our"-VMs are scheduled to all of the Hypervisors, we will get a "no host found" exception.
What we would need is kind of soft-anti-affinity. As long as it is possible, OpenStack should schedule VMs on different nodes, but as soon as it is not possible any more, OpenStack should accept that it needs do deploy VMs to an already used Hypervisor.

We probably can create a ServerGroup in the cluster actuator for master nodes. For worker nodes we might think about using its own group, but implement the fuzzy scheduling in the machine actuator. Like. Count the number of failures due to "no host found", if that increases $MAX, try to spin up a VM without servergroup.
But I want hear other opinions on this.

**Comment by gdoctor** [comment]
It's weird that their anti-affinity mode doesn't handle these edge cases for us, or at least make them configurable. I definitely could see this helping out with the stability of master nodes in production environments (assuming HA control plane); others might argue that they can achieve this by using different availability zones. 

However, I feel like we should leave out server groups for worker nodes, since each implementing team will have very different requirements and resources: worker node count, physical hardware available, etc. Defaulting to either affinity or anti-affinity could quickly lead to 'unknown' behavior in the eyes of the client.

**Comment by ainmosni** [comment]
I would love this feature, but it should be something that's optional and probably off by default.

When it's on, though, I would like it to create a new servergroup if the already existing servergroup is "full".

**Comment by chrigl** [comment]
The implementation approach I proposed in #275 adds a way to define scheduler hints on individual machines. In it's simplest form, just a Server Group can be passed to nova.

**Comment by oadivtal** [comment]
/reopen

Found this issue when I wanted to implement adding Server Groups in CAPO.

Will submit a new PR which is heavily based on @chrigl 's work in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/275/

**Comment by jichenjc** [comment]
yes, please be aware the master is based on v1alpha2 now and it may suprise you a little bit @oadivtal
