### ISSUE TITLE
Deprecating/Replacing securityGroups field from OpenStackMachineTemplate ports

### ISSUE THREAD

**Issue by Xenwar** [kubernetes-sigs/cluster-api-provider-openstack#1251]
/kind feature

**Describe the solution you'd like**
With the PR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1246, we have introduced a new field
`OpenStackMachineTemplate.spec.template.spec.ports.securityGroupsFilters.`

Before that, there was only one such field, OpenStackMachineTemplate` .spec.template.spec.ports.securityGroups` which is a lit of UUIDs.

I would like to deprecate the older field for two reasons. 

1. It is restrictive in that allows only specifying UUIDs
2. It is not the same as what is at intense level, shown below. 

```
kubectl explain OpenStackMachineTemplate.spec.template.spec.securityGroups
KIND:     OpenStackMachineTemplate
VERSION:  infrastructure.cluster.x-k8s.io/v1alpha5
RESOURCE: securityGroups <[]Object>
DESCRIPTION:
     The names of the security groups to assign to the instance
FIELDS:
   filter       <Object>
     Filters used to query security groups in openstack
   name <string>
     Security Group name
   uuid <string>
     Security Group UID
```

In favour of uniformity, I intend to 

- Remove `ports.SecurityGroups`
- Rename the new field `ports.securityGroupsFilters` to `ports.securityGroups`

**Anything else you would like to add:**

I would like to know if this breaks existing deployments and if it is ok to start coding and If there are any side effect this may introduce.

**Comment by jichenjc** [comment]
given we are still alpha version, I think we didn't guarantee the version compatible (actually we already did so)
thus, I see no reason we can't do it given the previous PR is already merged and it covers the deprecated feature

**Comment by Xenwar** [comment]
@jichenjc Thanks.

**Comment by apricote** [comment]
Making these changes to the CRD is breaking change which requires a new version of the CRD (probably `v1alpha6`?)

**Comment by mdbooth** [comment]
> Making these changes to the CRD is breaking change which requires a new version of the CRD (probably `v1alpha6`?)

Yes, definitely!

**Comment by mdbooth** [comment]
However, I do think it's appropriate to make these consistent.

**Comment by lentzi90** [comment]
/reopen
I'm working on this

**Comment by lentzi90** [comment]
After staring at the code for a while and implementing some conversions and tests for this, I'm not convinced it is a good idea to rename `securityGroupsFilters` to `securityGroups`. I would instead suggest to keep `securityGroupFilters` as is and just remove `securityGroups`. This is easier to handle in the conversions and much easier for users deal with also.

The old `securityGroups` field would be removed, the new `securityGroupFilters` would remain as is. Any old `securityGroups` can easily be converted to `securityGroupFilters` and they can be used in parallel in v1alpha6. In v1alpha7 `securityGroups` would be dropped.

The originally suggested change in this issue was to remove the (old) `securityGroups` and then rename `securityGroupFilters` to `securityGroups`. I think this is unnecessary and just makes things more confusing and complicated.
