### ISSUE TITLE
Ability to mount additional volumes

### ISSUE THREAD

**Issue by Goend** [kubernetes-sigs/cluster-api-provider-openstack#1286]
/kind feature

**Describe the solution you'd like**
openstack template  only has rootvolume, but i want to my own volume

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mdbooth** [comment]
Is there any reason you wouldn't just use a bigger root volume?

**Comment by Goend** [comment]
Because etcd has high requirements on the performance of the disk, on a disk, I am worried that other programs will affect it.And in our environment, we will give the etcd    high performance disk, but the system  disk  cannot use high performance  disk

**Comment by mdbooth** [comment]
Is this something you've tested? Did it fix the etcd problem? How would you configure the install image to mount the disk? What volume configuration did you use for improved performance?

This would be quite an invasive change. I can see the potential, but I'd want to be sure it's fixing a real problem before even thinking about the design.

**Comment by Goend** [comment]
This is a feature so I haven't tested it. The etcd community document recommends the use of ssd disk. We only need to support user disk mounting. As for how users use it, I think users can add partitions and initialization to the disk in the cloud.init file.

**Comment by jichenjc** [comment]
I knew the ETCD requirement .e.g SSD (OCP seems also has that)

basically I think we need 2 things 
1) volume attach including other lifecycle actions 
2) how to make the attach disk become k8s use

does cluster-api has #2 already e.g kubadm setup?

**Comment by Goend** [comment]
I think step 2 is too hard to achieve, so it should be implemented by users themselves

**Comment by Goend** [comment]
Since we don't know how the user wants to mount the disk and how many  disk, we should probably be more general and not just consider etcd, since I don't know much about this, you can ignore it

**Comment by jichenjc** [comment]
ok, again, I think the add volume still have value for some potential use cases, e.g 
CSI local storage might be helpful , we create /dev/vdb so that the local storage operator might consume it ..

**Comment by jichenjc** [comment]
I used the volume as source for local persistent storage source, this might be helpful 
(so that we don't need CSI in some cases..) this might be a use case 

```
root@jitest40:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig get pvc
NAME             STATUS   VOLUME                  CAPACITY   ACCESS MODES   STORAGECLASS    AGE
local-pvc-name   Bound    example-pv-filesystem   1Gi        RWO            local-storage   19m
root@jitest40:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig get pv
NAME                     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                    STORAGECLASS    REASON   AGE
example-pv-filesystem    1Gi        RWO            Delete           Bound       default/local-pvc-name   local-storage            23m



root@jitest40:~# cat pod.yaml
apiVersion: v1
.....
    volumeMounts:
    - name: localpvc
      mountPath: /data
  volumes:
  - name: localpvc
    persistentVolumeClaim:
      claimName: local-pvc-name
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
root@jitest40:~# kubectl --kubeconfig=./capi-quickstart.kubeconfig describe pv example-pv-filesystem
.....
Node Affinity:
  Required Terms:
    Term 0:        kubernetes.io/hostname in [capi-quickstart-md-0-748qj]
Message:
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /dev/vdc

```

**Comment by Goend** [comment]
Here are some ideas for etcd data disks in capi
https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20200423-etcd-data-disk.md

**Comment by jichenjc** [comment]
thanks for the sharing , I read the proposal and seems CAPI does support the infra already
so maybe from CAPO side we need honor those and provide related support for such use case..thanks :)

**Comment by mdbooth** [comment]
@mnaser

**Comment by jichenjc** [comment]
Reopened just now , I personally don't have too much time on this issue recently
I think it should be a change that need API spec update but we have various samples already ..

@javiku not sure you have time to work on this ,FYI

**Comment by dulek** [comment]
I like the separate controller idea.

**Comment by seanschneeweiss** [comment]
Also surprised that CAPI already has support for this.
That is how CAPZ moved etcd to a different data disk: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/661

**Comment by mdbooth** [comment]
Ping @EmilienM

**Comment by mkjpryor** [comment]
@mdbooth 

FWIW I think I prefer the `DataDisks` on the machine resource where the volumes take the machine name plus a suffix, like what the Azure provider implemented, rather than another CRD. Unless there is a very good reason for implementing the additional complexity?

Is anyone actively looking at this? We might have a customer who needs this relatively soon and may be able to commit some resource to a patch - no commitment though! 😉

**Comment by mdbooth** [comment]
@mkjpryor @EmilienM is looking at a related aspect of this, which is why I pinged him. There could well be an opportunity to work together on this.

The related aspect is using the local disk as a data disk and booting from volume, specifically for etcd. From Nova's POV you boot a flavor with e.g. a 5G ephemeral disk. You specify a block device mapping which boots from a separately-created root volume and maps the local ephemeral disk second.

**Comment by mkjpryor** [comment]
@mdbooth 

Thanks for the clarification - that sounds quirky! I can see why that wouldn’t be so easily supported by a `DataDisks` option.

Another related thing that we are keen to look at is making better use of the ephemeral disk of flavors (as opposed to the root disk). I think all the primitives already exist to do this though - it’s just a case of deciding where to mount it.

**Comment by EmilienM** [comment]
@mkjpryor Yes I'm going to work on that, very likely in the next months.

I'm sad that I didn't came across this issue before I kicked off this small prototype (will be re-worked): https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1640

I personally think that we should follow https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/661 as it's a strong reference and following https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20200423-etcd-data-disk.md.

Now for the controller separation question, I don't have enough context now to provide an opinion. I'll spike on this in the next weeks.

**Comment by mdbooth** [comment]
You're absolutely right that:
* There is no requirement to store volume ids in the status
* Even if we did store volume ids in the status, we would still have to check for them by other means on delete.

Storing state in the status would essentially be an optimisation because if the volumes are present in the status there's no need to check cinder at all during reconcile, and if we do check cinder it will be by volume id instead of name/tag, which is more efficient. As an optimisation, though, we don't need to implement it.

The most important things are:
* Volume creation has an independent flow which the controller must call before server creation
* Volume deletion has an independent flow which the controller must call after server deletion

I agree we don't need to consider the deletion of volumes from the spec.

I very much like the idea of tagging volumes. I'd probably tag them with both the machine and the cluster.

**Comment by mkjpryor** [comment]
Agreed. We can optimise later if we feel we need it. I think this keeps the patch nice and simple.
