### ISSUE TITLE
Add more information to Running E2E tests locally

### ISSUE THREAD

**Issue by h1r0mu-nic** [kubernetes-sigs/cluster-api-provider-openstack#1356]
/kind documentation

When I first tried to run [E2E tests locally](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/development/development.md#running-e2e-tests-locally), I faced some problems such as machine spec is not enough, neutron trunking must be configured, image size have to be less than 20MB, etc.

After reading [Hacking CI for the E2E tests](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/development/ci.md#hacking-ci-for-the-e2e-tests) and codes under [hack/ci](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/tree/main/hack/ci), everything works fine.

My suggestion is to add following items, which can be retrieved from aforementioned Hacking CI and codes, to [E2E tests locally](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/development/development.md#running-e2e-tests-locally).

- System requirements
- Availability zones
- Services
- Clouds.yaml

**Comment by mdbooth** [comment]
Definitely in favour of better developer documentation. Are you able to submit patches?

I think @stephenfin has also been running these locally recently. Any thoughts?

**Comment by stephenfin** [comment]
I wasn't running these, I was running github.com/kubernetes/cloud-provider-openstack e2e tests. I wrote a very high level doc on running there, which you can see athttps://github.com/kubernetes/cloud-provider-openstack/pull/2006. Unfortunately I couldn't get more detailed because the tooling isn't there (yet) to easily run this stuff yourself by executing e.g. a script or Makefile target.

**Comment by jichenjc** [comment]
>>>If you're okey with that, I'll open PR.

yes, please :) , thanks for the help~
