### ISSUE TITLE
resource creation in CAPO discussion

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-openstack#1358]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This trigger a discussion on the topic of whether we should create `static` resource in CPO

we saw some discussions in 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1344
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1274

basically those resources are `pre-defined` and `static`, e.g the admin knows they exist and how they are orignized
for example, CNI has calico and we are going to support more ,but those seucirty groups for CNI are static and created once
,also the flavor requirement of #1344 apply as well 

pros and cons exist if we choose to let CAPO create those because it can provide flexiblity of CAPO but it will increase the code complexity as it might be easier to achieve through ansible/bash, for example, a few json array can help create the CNI security group and with bash a few lines can create it and CAPO is able to use it (maybe with same param check and whether it exist but it's simple) 

so I think we may reach agreement on such and provide guide/comment on other potential questions /requirement
 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mdbooth** [comment]
I think these are very different topics. The issue in #1344 is that the requested capability requires us to manage admin credentials rather than regular tenant credentials. That's a significant design change and I think we'd want an incredibly thorough use case analysis before going down that road. It would also have to be worthwhile to make such a significant change compared to the alternatives, i.e. creating the flavor in advance with a different tool. We would also have to weigh it against the additional testing burden of ensuring we can continue to operate with tenant credentials whilst also testing a feature which requires admin credentials. I expect that a significant proportion of our users would not permit CAPO to use admin credentials.

As for #1274 I think we do have a need for this. However we implement it, I expect the UX to involve selecting an appropriate additional manifest file when deploying. This would mean we could maintain config for the most common ones in-tree, whilst allowing users to customise as needed or implement completely new ones without modifying code. This could reasonably be either a new CRD or a config file.

**Comment by jichenjc** [comment]
ok, I didn't pay attention to the `admin` cred, this might be different .. need give more thought
