### ISSUE TITLE
Rework OS support

### ISSUE THREAD

**Issue by ainmosni** [kubernetes-sigs/cluster-api-provider-openstack#159]
Right now, our generation scripts only support "CentOS" and "Ubuntu". We should add an option for Container Linux and/or Flatcar to them so that people can easily spin up clusters based on that.

**Comment by flaper87** [comment]
TBH, I've always seen the CentOS/Ubuntu scripts as examples and not necessarily as something we support. I wonder how far we should push this and allow for more distros to be added.

We have some options:

1) We accept distro support as something that can live in this repo. This means we would move the scripts to their own dir (out of examples) and, hopefully, have subteams dedicated to them (a subteam of maintainers)

2) We stick with the 2 we have and let people maintain production-ready scripts outside this repo.

There is (was?) an effort to consolidate these scripts but I'm not sure how far that got (or will get considering we're talking about deployment tools here).

@chrigl @chaosaffe @tomassedovic any thoughts? opinions?

**Comment by flaper87** [comment]
>     1. We accept distro support as something that can live in this repo. This means we would move the scripts to their own dir (out of examples) and, hopefully, have subteams dedicated to them (a subteam of maintainers)

although option 2 sounds easier from a maintenance standpoint, I think 1 is our best option for now. We need these scripts to explain and demonstrate the actuator capabilities and it may be time for us to call them something else rather than examples.

We can implement some guidelines and requirements that need to be met before accepting new "distros". Having CI could be one of them, for example.

**Comment by ainmosni** [comment]
@flaper87 I agree, I think we should treat them as reference implementations. Having a nice working reference will make it much easier to get going with the project, which will lead to more users and then hopefully more contributors.

**Comment by chrigl** [comment]
I would also prefer to have a reference implementation rather than "just" examples.

Maybe we could use this ticket to come up with something more formalised than just a bash-script. I am thinking of a Container Linux Config solution for ContainerLinux... while we could reimplement Ubuntu and CentOS, using cloud-init (for sure in a separate ticket).

**Comment by ainmosni** [comment]
Should we rename this ticket and change the scope then or shall we close this and create a new ticket?

**Comment by flaper87** [comment]
@ainmosni Let's rename this one and keep the history.

I've done quite some work on other fronts to allow for container linux to be supported. The way we render the user data and where we get it from allows for ignition configs to be passed to the nodes.

As a starting point, I think we could move the examples into a `templates` dir and create a subdir per operating system.

**Comment by flaper87** [comment]
@ainmosni hey, are you working (or planning to work) on this? I think it's time to get this done :smiley:

**Comment by chrigl** [comment]
/assign @chrigl 

I started on it, and am pretty far. Migrated everything to a cloud-init format. Today starting to integrate it into machine actuator.
