### ISSUE TITLE
Generate kubeconfig rather than getting it from the master nodes

### ISSUE THREAD

**Issue by flaper87** [kubernetes-sigs/cluster-api-provider-openstack#174]
We're currently using ssh to get the kubeconfig from the master nodes. We should find a better way to do it that doesn't depend on ssh and on having access to the master nodes' network.

```go
func (d *DeploymentClient) GetKubeConfig(cluster *clusterv1.Cluster, master *clusterv1.Machine) (string, error) {
	ip, err := d.GetIP(cluster, master)
	if err != nil {
		return "", err
	}

	homeDir, ok := os.LookupEnv("HOME")
	if !ok {
		return "", fmt.Errorf("unable to use HOME environment variable to find SSH key: %v", err)
	}

	machineSpec, err := openstackconfigv1.MachineSpecFromProviderSpec(master.Spec.ProviderSpec)
	if err != nil {
		return "", err
	}

	result := strings.TrimSpace(util.ExecCommand(
		"ssh", "-i", homeDir+"/.ssh/openstack_tmp",
		"-o", "StrictHostKeyChecking no",
		"-o", "UserKnownHostsFile /dev/null",
		fmt.Sprintf("%s@%s", machineSpec.SshUserName, ip),
		"echo STARTFILE; sudo cat /etc/kubernetes/admin.conf"))
	parts := strings.Split(result, "STARTFILE")
	if len(parts) != 2 {
		return "", nil
	}
	return strings.TrimSpace(parts[1]), nil
}
```

**Comment by chrigl** [comment]
There are already efforts in https://github.com/kubernetes-sigs/cluster-api/issues/122 to get rid of SSH... while the initial thought was to postpone cert generation to the actual node-setup.

**Comment by chrigl** [comment]
Just thinking out loud... We talked about this could probably work. My idea is:
In `clusterctl` create a `remote-bootstrap-secret.yaml` in form of a bootstrap-token with an additional group (see below). This should be only valid for lets say 20 minutes. The yaml data is passed as a shared secret within the userdata. But because it is only valid for a short period of time, we in the first place I would accept the fact, that it in theory could be intercepted. Even though unlikely.

Jump to the master node. Bootstrapping as usual with `kubeadm init`. After bootstrap creating a secret containing an `admin.conf`. Also creating the shipped `remove-bootstrap-secret`, and adding a Role+RoleBinding to give access to the `admin.conf`-secret.

Back at `clusterctl`... we can grab the `admin.conf` with our bootstrap-token, with tls verification disabled (because we don't know the ca pub yet). Maybe we should grab and instantly delete it.

Potentially we also could try to get and verify the ca pub from namespace `kube-public`, and verify it. So we won't need to disable tls verification. But I would consider this to be a second (and separate) step.

However... this is just a rough scratch out of my head.

**Comment by flaper87** [comment]
> Just thinking out loud... We talked about this could probably work. My idea is:
> In `clusterctl` create a `remote-bootstrap-secret.yaml` in form of a bootstrap-token with an additional group (see below). This should be only valid for lets say 20 minutes. The yaml data is passed as a shared secret within the userdata. But because it is only valid for a short period of time, we in the first place I would accept the fact, that it in theory could be intercepted. Even though unlikely.
> 
> Jump to the master node. Bootstrapping as usual with `kubeadm init`. After bootstrap creating a secret containing an `admin.conf`. Also creating the shipped `remove-bootstrap-secret`, and adding a Role+RoleBinding to give access to the `admin.conf`-secret.
> 
> Back at `clusterctl`... we can grab the `admin.conf` with our bootstrap-token, with tls verification disabled (because we don't know the ca pub yet). Maybe we should grab and instantly delete it.
> 
> Potentially we also could try to get and verify the ca pub from namespace `kube-public`, and verify it. So we won't need to disable tls verification. But I would consider this to be a second (and separate) step.
> 
> However... this is just a rough scratch out of my head.
> 
> OK... This does not exactly match the ticket description... but I think you get it. We don't have to generate and inject the CA into VMs rather than short-term valid bootstrap-token. I went with bootstrap-token because of being able to define an expiration.

I like this solution!

The manager will be able to access the kubeconfig from within the cluster whereas `clusterctl` will download it asap with the temporary token. The downside of this approach is that it adds a time limit to the bootstrap process. Admittedly, if your deployment using `clusterctl` is taking longer than 20mins, you may have bigger problems... but still.

**Comment by jichenjc** [comment]
@flaper87 just curious, we removed the ssh requirements in #192
I understand this is a to do item but after ssh removal and before we have solution, how to we get kubeconfig file?

**Comment by jichenjc** [comment]
ok, I realized the removal is only for master/node interaction and the current logic for deployer is kept, sorry for disturbing...
