### ISSUE TITLE
API Loadbalancing with Keepalived/HAProxy

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/cluster-api-provider-openstack#1755]
/kind feature

**Describe the solution you'd like**
Support the deployment of OpenShift clusters which use keepalived and HAProxy.

By default, OpenShift clusters expect there to be an internal API port on the cluster network which is not attached to any server. This port has a floating IP on the external network.

All control plane machines have a port on the cluster network which has an additional allowed address pair such that it can receive traffic for the internal API port. This allows a keepalived process running on each control plane machine to 'take' the internal API port as necessary.

We need to be able to specify a CAPO loadbalancer configuration which supports this.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by zioc** [comment]
This looks very interesting! As we used to discuss about this kind of api exposition solution in [another issue](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1265#issuecomment-1160772495), I just wanted to mention that we have the exact same use case in [sylva project](https://gitlab.com/sylva-projects/sylva-core) where we use metallb or kube-vip to expose cluster IP.

In order to follow-up with your comment in this thread, it is also possible to expose cluster IP with metallb, the only issue is that is not easy to install it with using kubeadm control plane provider (as kubeadm tries to reach the api endpoint, and metallb indeed requires the api to be available to set-up, there is a chicken and egg issue) but it works perfectly with kube-vip that is [designed to be run as a static pod](https://kube-vip.io/docs/installation/static/). On the other hand, metallb works perfectly while using [rke2 controlplane provider](https://github.com/rancher-sandbox/cluster-api-provider-rke2) that has the capability to deploy charts from static manifests.

For now we were adding allowed address pair to control-plane machines templates, but it would be great if these external load-balancing options would be officially supported by this provider. One point to mention is that it is also necessary to ensure that the virtual IP will not be allocated by neutron to another port, for that purpose we are currently creating a port in neutron to reserve this address (it remains down and unbound) using a sidecar operator, if would be great if capo controller could take care of that point too.

**Comment by chess-knight** [comment]
Hi @zioc.
I am utilizing kube-vip for the HA control-plane on OpenStack using CAPO. I will be grateful if you can share minimal example (manual steps for OpenStack and CAPO manifests) of how to do that. If I understand correctly, I need to create a network and port with a fixed IP beforehand and then somehow configure CAPO, but I have not been successful so far.
Thanks
