### ISSUE TITLE
Use created networks for machines.

### ISSUE THREAD

**Issue by ainmosni** [kubernetes-sigs/cluster-api-provider-openstack#205]
Right now, we have the option of having an OpenStack network created when a cluster is created, except there is no way to have the machines actually use this network. This makes the actual usage of this network a bit clumsy as you first have to create a cluster, wait for the network to be created, get the status of the cluster and then manually fill it in in the machine spec. We should add a `fromCluster` (or similar) option to machineSpec.providerSpec.networks, that will look at a specified cluster and uses the network that's defined in the status.

**Comment by jichenjc** [comment]
I can work on that if no one already work on it

**Comment by ainmosni** [comment]
Yeah, I was thinking to just check the status, if it's filled in, go ahead, else abort.

**Comment by jichenjc** [comment]
basic idea will be Add a bool 'fromCluster' in NetworkParam (inside OpenstackProviderSpec) or a special value for FixedIp (such as 'fromcluster') so that when creating machine, we won't use the ID , instead, when doing InstanceCreate , we will query the info from apis/openstackproviderconfig/v1alpha1/types.go:Network , and use that info, of course , need double check whether the network is ready or not before use it....
