### ISSUE TITLE
Add support for security group names instead of UUIDs

### ISSUE THREAD

**Issue by luis5tb** [kubernetes-sigs/cluster-api-provider-openstack#234]
Due to the changing the way VMs are created to enable trunk support (first create the port and then the VM that uses it), OpenStack nova is no longer doing the conversion from security group name to UUIDs, as the security group is passed while creating the port. Thus there is a requirement for stating security groups UUIDs instead of names. SG names support should be re-added

**Comment by flaper87** [comment]
I agree, although, I'd like to propose a different approach.

Instead of just adding support for SG names, can we add support for FilterParams just like we did with networks? We should be able to filter SGs by name, tags, and other attributes. This will make the interaction with OpenStack clouds easier.

For example, in the `openshift-installer` we filter networks and security groups based on tags. All the resources that respond to a specific query are then added to the instance.

**Comment by iamemilio** [comment]
I can pick this up if you want. I may deviate from the filter syntax we used before thought. I think its a lot cleaner if you can do this:
SecurityGroups:
   - < [ name | id ] > 
     [ filters ]

**Comment by iamemilio** [comment]
I'll take this
/assign @iamemilio

**Comment by iamemilio** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/236
ok to close?

**Comment by iamemilio** [comment]
@luis5tb can you close this issue
