### ISSUE TITLE
worker node do not have roles

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#298]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

After my cluster was provisioned, I found that the worker node role is none, but master node do have a role named as master, so I think that we should also add a role for worker node as well.

```
root@liugya-master-cpr5j:~# kubectl get nodes
NAME                  STATUS   ROLES    AGE     VERSION
liugya-master-cpr5j   Ready    master   3h50m   v1.14.0
liugya-node-ngw58     Ready    <none>   3h47m   v1.14.0
```

/cc @jichenjc @chrigl 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
I found same situation, will something like 'worker' enough @gyliu513 ?

**Comment by gyliu513** [comment]
@jichenjc Yes, I think we can set it as `worker` first.

**Comment by jichenjc** [comment]
I am working on this, seems 

 kubectl label node minikube node-role.kubernetes.io/worker=

works, however, the issue is we need create master first then apply the nodes after that
then we are done..so need some place to add this logic,maybe in cluster-api??

 kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   33h   v1.12.7
root@kvm-017751:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu# kubectl label node minikube node-role.kubernetes.io/worker=
node/minikube labeled
root@kvm-017751:~/go/src/sigs.k8s.io/cluster-api-provider-openstack/cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu# kubectl get nodes
NAME       STATUS   ROLES           AGE   VERSION
minikube   Ready    master,worker   33h   v1.12.7
