### ISSUE TITLE
Enable installing multiple controller planes cluster

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-openstack#346]
/kind feature

I did not found a solution for how to install an HA cluster with OpenStack provider, seems to be a feature needs to be implemented?

/cc @dims @jichenjc @chrigl

**Comment by hchenxa** [comment]
refer https://kubernetes.io/docs/setup/independent/high-availability/ to setup HA environment with kubeadm.

seems like we need loadbalance for HA environment.

**Comment by gyliu513** [comment]
Yes, but not sure if the cluster api has logic to handle the creation of master nodes, there are some issues at https://github.com/kubernetes-sigs/cluster-api/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+HA

**Comment by jichenjc** [comment]
I think maybe we need try 1+ masters case, I remember they somewhere I see it doesn't support multiple master (not 100% sure), we may try that case first then see how we can handle it

and if we need Loadbalancer, we'd better refer to https://github.com/kubernetes/cloud-provider-openstack/tree/master/pkg/ingress instead create by our own..

**Comment by hidekazuna** [comment]
I found cluster-api-provider-aws realises[ multi-node control plane](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/docs/creating-multinode-controlplane-clusters.md#creating-clusters-with-a-multi-node-control-plane--)

**Comment by gyliu513** [comment]
Thanks @hidekazuna for the info, this is really helpful.

@detiber , any comments for this? Do you think each cloud provider need to implement this or this should be done by cluster-api?

**Comment by detiber** [comment]
If there is a need to support HA using the ClusterAPI v1alpha1 types, then it will need to be implemented on a per-provider basis. I hope that we'll have a better solution for v1alpha2 and beyond, but those proposals are still being defined as part of the workstreams effort.

For the AWS provider, we use a 'set' label on the machine to differentiate Control Plane vs worker node, and then inject different user data into the machine instantiation depending on whether it is the first control plane machine or not: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/services/ec2/instances.go#L168-L265

`clusterctl` already supports deploying a machines.yaml file that contains multiple Control Plane machines (which it uses the machine.spec.version configuration to determine). Both the 0.1.1 tag and the `release-0.1` branch already contain this support.

One other thing to note is that the AWS provider uses an ELB to represent the API endpoint regardless of the number of control plane instances, so I'm not sure how well the cloud-provider ingress would fill that gap without introducing a chicken and egg situation. It's been a few years since I've built a cluster on OpenStack, but I would have hoped that LBaaS v2 was commonly available by now.

**Comment by gyliu513** [comment]
> clusterctl already supports deploying a machines.yaml file that contains multiple Control Plane machines (which it uses the machine.spec.version configuration to determine). Both the 0.1.1 tag and the release-0.1 branch already contain this support.

Thanks @detiber , do we have some document for this? With this multiple Control Plane machine, can I say this is also HA cluster?

**Comment by detiber** [comment]
@gyliu513 I think it depends, we try to avoid calling it HA in the AWS provider today because we do not deploy the control plane instances across Availability Zones by default (it is possible to do, but it requires pre-configuration and manual configuration of the Machine resources). But that is a choice that we made as a project. I think it would be fine to refer to it as HA as long as the failure modes/domains are explicitly called out.

**Comment by gyliu513** [comment]
Cool, thanks @detiber , I think we can first enable multiple control planes for openstack provider.

**Comment by jichenjc** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/889 has some implementation on cluster-api
let's see whether we need additional stuffs in provider openstack or just close this without any changes
/assign

**Comment by sbueringer** [comment]
I'll implement it here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/382

**Comment by jichenjc** [comment]
duplicate to #382 
/close
