### ISSUE TITLE
AvailabilityZone support for Cinder Volumes and RootVolume when Instance spawned on cinder

### ISSUE THREAD

**Issue by ITD27M01** [kubernetes-sigs/cluster-api-provider-openstack#554]
/kind feature

**Describe the solution you'd like**
In the case of real clouds there are multiple availability zones for different services (Nova/Neutron/Cinder). For the consistency provided by cloud services in some datacenter this services are marked by availabilty_zone attribute.

There is no support for availability zones of cinder volumes and as a result we cannot create instances on the cinder boot volume on specified availability zone.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ITD27M01** [comment]
https://github.com/gophercloud/gophercloud/issues/1965

**Comment by jichenjc** [comment]
are you suggesting cluster-api-provider openstack honor the changes you provided? as I don't fully understand the requirements here..

@sbueringer FYI

**Comment by ITD27M01** [comment]
@jichenjc My apologies for the delay. Yes, I would to suggest to allow specify AvailabilitZone for created volume.

**Comment by jichenjc** [comment]
@ITD27M01 as gophercloud/gophercloud#1965 indicated, there is no way to create volume from choose az when do boot from volume

so please
1) make sure the purpose of using cluster-api-provider-openstack, it's helping you define k8s cluster and it need some input from customer some
2) there is a gap currently in the code, which is you need input the cinder volume ID 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/9e63a34907bca1829185fb5fca1f56deaba5ab4b/pkg/cloud/services/compute/instance.go#L232
in machine spec file, there is no way to create the volume on the fly now
3) in order to achieve the function you proposed, we need add such create volume thing during machine creation and in turn obtain the volume ID 

so please help to check the use case, are you using cluster-api to define k8s cluster on opentack and the boot from volume fetaure you are using can't select the AZ? temp solution is you need create the volume on your desired az then provide it to machine spec file, let us know it then we can consider add volume creation on the fly later on , thanks

**Comment by ITD27M01** [comment]
as gophercloud/gophercloud#1965 indicated, there is no way to create volume from choose az when do boot from volume
