### ISSUE TITLE
E2E test using Cluster API test framework

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#577]
/kind feature

**Describe the solution you'd like**

We can update E2E test to use Cluster API test framework.

**Anything else you would like to add:**

Cluster API test framework is guided in [The Cluster API Book](https://cluster-api.sigs.k8s.io/developer/e2e.html).

**Comment by sbueringer** [comment]
The issue is basically implemented. After those 3 PRs have been merged it can be closed:
  * [Implement conformance via test framework](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/782)
  * [golangci-lint](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/797)
  * [add e2e tests for all flavors #798](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798)

**Comment by sbueringer** [comment]
Last 2 open PRs:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798
* https://github.com/kubernetes/test-infra/pull/21536

I"ll close the issue after those.
