### ISSUE TITLE
Use Keystone application credential

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes-sigs/cluster-api-provider-openstack#578]
/kind feature

**Describe the solution you'd like**

Currently we use only user name and password for authentication with OpenStack Keystone.
Moreover,  we can use  [Keystone application credential](https://docs.openstack.org/keystone/latest/user/application_credentials.html).

**Anything else you would like to add:**

External OpenStack cloud provider already implemented.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md#global

**Comment by jichenjc** [comment]
https://github.com/kubernetes/cloud-provider-openstack/pull/426/files

we can refer to this PR

**Comment by zufardhiyaulhaq** [comment]
Hi, I want to take this issue, what is the expected time to finish this?

**Comment by sbueringer** [comment]
@zufardhiyaulhaq I assume as long as you're actively working on it it's fine.

@hidekazuna Correct me, if I'm wrong.

**Comment by hidekazuna** [comment]
@zufardhiyaulhaq Thanks for taking this issue! This issue is no time limit, and no dependency.

**Comment by jichenjc** [comment]
@hidekazuna @sbueringer @zufardhiyaulhaq 

I did some test and I think it's not that easy...

so the application ID is eligible to be used to be auth, you need modify 2 places
one is 

`capi-openstack-cloud-config` ,you need update the Secret to contains correct clouds.yaml
my test shows it's easy to do so and I can successfully create a `machine` after the modification

however, we need modify `KubeadmControlPlane` so that the cloud.conf is updated and the cloud provider use the `/etc/kubernetes/cloud.conf` definition, this is not doable because legacy cloud provider doesn't honor this now , we need fix https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/489 first then switch to external cloud provider and use the application ID

**Comment by hidekazuna** [comment]
@jichenjc Thanks for investigating. It is not expected..

I found cluster-api-provider-azure has [external cloud provider option](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/docs/topics/external-cloud-provider.md), seems not difficult to follow. If you does not try external cloud provider, I will try #489.

**Comment by jichenjc** [comment]
yes, please :) , I don't know the azure implementation ~

**Comment by jichenjc** [comment]
after https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/595 is done,
we should be able to solve this problem ,I can use application id based on 595 .
