### ISSUE TITLE
Kubernetes service type LoadBalancer doesn't assign external IP 

### ISSUE THREAD

**Issue by eratnch** [kubernetes-sigs/cluster-api-provider-openstack#580]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I deployed a workload ha cluster with 3 control plane and 1 worker machines on devstack with octavia.
Everything looks fine in the target cluster.
However when i started creating a service of type load balancer the service gets created but the external ip is always pending.

Here are outputs from my target cluster

kubectl --kubeconfig tgtcluster.kubeconfig get nodes
NAME                        STATUS   ROLES    AGE   VERSION
ostgt-control-plane-f9wl5   Ready    master   22h   v1.17.3
ostgt-control-plane-jxnxc   Ready    master   22h   v1.17.3
ostgt-control-plane-qq285   Ready    master   22h   v1.17.3
ostgt-md-0-xb96g            Ready    <none>   22h   v1.17.3

kubectl apply -f https://k8s.io/examples/service/access/hello.yaml --kubeconfig tgtcluster.kubeconfig
deployment.apps/hello created

kubectl apply -f https://k8s.io/examples/service/access/hello-service.yaml --kubeconfig tgtcluster.kubeconfig

kubectl apply -f https://k8s.io/examples/service/access/frontend.yaml --kubeconfig tgtcluster.kubeconfig

kubectl --kubeconfig tgtcluster.kubeconfig get services

NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
frontend     LoadBalancer   10.98.53.249   <pending>     80:31790/TCP   10m
hello        ClusterIP      10.99.49.129   <none>        80/TCP         10m
kubernetes   ClusterIP      10.96.0.1      <none>        443/TCP        24h

The octavia load balancer is ONLINE and ACTIVE and the vip is mapped to floating ip (in this case 172.24.4.120).

**What did you expect to happen:**
frontend service is assigned the floating ip
Frontend service is accessible by curl http://${EXTERNAL_IP}

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 
clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.6", GitCommit:"beff1e1df8e80d3a4fdb996c86409793ee491d47", GitTreeState:"clean", BuildDate:"2020-05-15T16:00:09Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):

kubectl --kubeconfig tgtcluster.kubeconfig version --short
Client Version: v1.18.5
Server Version: v1.17.3

- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
my understanding is we are working on providing a cluster here
then how to manage the internal of the cluster depends on https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-octavia-ingress-controller.md ? 
so it's a bigger step if we want to integreate those?

**Comment by eratnch** [comment]
@jichenjc  I have followed https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/expose-applications-using-loadbalancer-type-service.md guide to create a load balancer service. But the external IP is always pending. I am trying to make sure that my workload cluster is capable of supporting LB. I would appreciate if any documentation or pre-requisite is available to make it work since this is a practical use case in my opinion.

**Comment by jichenjc** [comment]
@hidekazuna I always tried non-Lb case before, can you provide some insight here?

**Comment by hidekazuna** [comment]
@jichenjc This issue comes from discussion https://kubernetes.slack.com/archives/CFKJB65G9/p1594346254144700?thread_ts=1590866877.082500&cid=CFKJB65G9

### Problem

For using the OpenStack load balancer as service type LoadBalancer, the [LoadBalancer] section must be written in the `cloud.conf` like the following.
```
[LoadBalancer]
subnet-id=6937f8fa-858d-4bc9-a3a5-18d2c957166a
```

The cloud.conf content is created by [env.rc](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/templates/env.rc) which does not include LoadBalancer section. We can not use the OpenStack load balancer as service type LoadBalancer straightforward.

### Solution

1. Create network/subnet(may need router also)
2. Add the [LoadBalancer] section before [Global] section in the [env.rc](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/templates/env.rc) 
3. Run [env.rc](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/templates/env.rc) as usual and set other environment variables as usual, too.
4. Run `clusterctl config cluster` as usual.
5. Update the generated template
```conf
# nodeCidr: 10.6.0.0/24
  network:
    id: <your network id>
```
6. Apply the template

P.S. I want to try this issue when approaching [the external cloud provider issue](#489 )

**Comment by hidekazuna** [comment]
I hope someone will find a better solution 😃

**Comment by sbueringer** [comment]
@hidekazuna Noboy is forced to use the env var `OPENSTACK_CLOUD_PROVIDER_CONF_B64` calculated by the env.rc. You can always just set it by ourselves. Obviously it would be better if it just works out of the box :)
