### ISSUE TITLE
Improve security group reconcilation

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api-provider-openstack#771]
/kind feature

Currently the security groups get reconciled by deleting all existing rules and creating all wanted rules if only a single rule does not match (see https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/services/networking/securitygroups.go#L111).

If in future the hardcoded security groups get changed and capo reconciles it will delete and recreate all security group rules which may result in connection drops.

**Describe the solution you'd like**

It is possible to create two lists:
* `rulesToCreate` (desired - observed)
* `rulesToDelete` (observed - desired)

And reconcile using them by
* deleting the rules in `rulesToDelete`
* creating the rules in `rulesToCreate`
* return `rulesToCreate + (rules which are in desired and observed)` 

**Anything else you would like to add:**

-

<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Imprint</a>
</sup>

**Comment by chrischdi** [comment]
I would be happy to contribute the improvement if it is considered good :-)

**Comment by jichenjc** [comment]
I think it's a reasonable change :) please go ahead 

@hidekazuna FYI

**Comment by hidekazuna** [comment]
Since ReconcileSecurityGroups only runs `openStackCluster.Spec.ManagedSecurityGroups: true`, we can avoid the situation by the following.

1. Update `openStackCluster.Spec.ManagedSecurityGroups` to `false` to stop running ReconcileSecurityGroups.
2. Update security groups following new hardcoded security groups manually.
3. Update CAPO
4. Update `openStackCluster.Spec.ManagedSecurityGroups` to `true`
5. Run ReconcileSecurityGroups again, desired = observed.

But your solution is still valid for accidentally updating security groups manually when `openStackCluster.Spec.ManagedSecurityGroups: true`

**Comment by chrischdi** [comment]
> Since ReconcileSecurityGroups only runs `openStackCluster.Spec.ManagedSecurityGroups: true`, we can avoid the situation by the following.
> 
> 1. Update `openStackCluster.Spec.ManagedSecurityGroups` to `false` to stop running ReconcileSecurityGroups.
> 2. Update security groups following new hardcoded security groups manually.
> 3. Update CAPO
> 4. Update `openStackCluster.Spec.ManagedSecurityGroups` to `true`
> 5. Run ReconcileSecurityGroups again, desired = observed.
> 
> But your solution is still valid for accidentally updating security groups manually when `openStackCluster.Spec.ManagedSecurityGroups: true`

Yes, this would have the result but needs manual actions to have a smooth migration :-)
