### ISSUE TITLE
Generated code may go to `$GOPATH/src` instead of in repo

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes-sigs/cluster-api-provider-openstack#801]
/kind bug

**What steps did you take and what happened:**

Found in https://github.com/kubernetes-sigs/cluster-api/issues/4185

We use [conversion-gen](https://pkg.go.dev/k8s.io/code-generator/cmd/conversion-gen) to generate some of the code. This command has an optional argument of `--output-base` that controls where the generated files are placed.

The default for this arg can vary. If `GOPATH` is set, then it will place files under `$GOPATH/src`. But if not set, it defaults to `./`, which is what we want to have the generated files within the repo.

The dependency on an environment variable is non-obvious and can cause stale files to be used if the user doesn't know about it. There also appears to be a difference whether running with the repo cloned within `$GOPATH/src` or elsehwere.

**What did you expect to happen:**

Files generated/over-written within the repo. In environment with GOPATH set, files were generated under `$GOPATH/src/api`.

**Comment by sbueringer** [comment]
@stmcginnis Thx for opening this issue here. I already saw the discussion in the cluster-api repo. 

Sounds good to me. I would just includ it in this PR: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798

 I already synced the Makefile there with the Makefiles of other providers, so it makes senses to just include it

**Comment by stmcginnis** [comment]
Sorry @sbueringer, I saw your comment too late. I'm fine with whatever. I'll leave this PR up in case we want a targeted change, but if you want to just include it in #798, that's fine too. Thanks!

**Comment by sbueringer** [comment]
Just saw you're PR. Let's run the tests to be save and then just merge it, I'll rebase my pr ;)

**Comment by sbueringer** [comment]
I have a bit of a strange setup locally so the fix seem to lead to problems here.

* I checked out the CAPO repo at `/home/sbuerin/code/src/sigs.k8s.io/capi-dev/cluster-api-provider-openstack`
* my GOPATH is set to `/home/sbuerin/code`

conversion gen is run via the Makefile with:
```bash
hack/tools/bin/conversion-gen \ 
        --input-dirs=./api/v1alpha3 \
        --output-file-base=zz_generated.conversion --output-base=/home/sbuerin/code/src/sigs.k8s.io/capi-dev/cluster-api-provider-openstack \
        --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
```

It then generates the conversion file at: `/home/sbuerin/code/src/sigs.k8s.io/capi-dev/cluster-api-provider-openstack/sigs.k8s.io/capi-dev/cluster-api-provider-openstack/api/v1alpha3/zz_generated.conversion.go`
(instead of ` `/home/sbuerin/code/src/sigs.k8s.io/capi-dev/cluster-api-provider-openstack/api/v1alpha3/zz_generated.conversion.go`)

So it has the following part twice `sigs.k8s.io/capi-dev/cluster-api-provider-openstack`. This seems to be the relative location in my `GOPATH`. Although I'm running with Go 1.16 so go modules should be (in most cases) used because it's default now.

Adding the following to the Makefile fixes it (cluster-api/Makefile does the same)
```bash
# Active module mode, as we use go modules to manage dependencies
export GO111MODULE=on
```

I'll open a PR for it

**Comment by stmcginnis** [comment]
Great catch! Adding the conditional logic of seeing the output base was due to this happening in GOPATH. I wonder if with your change that would even be necessary. We may be able to simplify some logic by setting that to 'on'.

I may test some more, but that's a great fix.

**Comment by stmcginnis** [comment]
Checked in `cluster-api` and `GO111MODULE` is already set to `on` there. So it doesn't look like that fixes the whole issue originally seen. But at least adding it here in this case does help, so that's great!

**Comment by sbueringer** [comment]
@stmcginnis Yeah I looked up if there's something different regarding go modules in the main repo and that's how I found the fix :)
