### ISSUE TITLE
"clusterctl config cluster" doesn't add mandatory service-account configuration in control-plane's api server

### ISSUE THREAD

**Issue by belomx** [kubernetes-sigs/cluster-api-provider-openstack#848]
/kind feature

It would be good if the "cluster config cluster" could add automatically or by a new argument the service-account configuration, otherwise the control-plane is going to fail to start the api-server container (error below).
Error of api server in the control-plane:
kube-apiserver fails init. receive "**--service-account-signing-key-file and --service-account-issuer are required flag**"
[https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/626](url)

To reproduce the problem, it's just necessary to follow the "quick start" for openstack.
[https://cluster-api.sigs.k8s.io/user/quick-start.html](url)

Create the "capi-quickstart.yaml" as below, will let the api server with the service account mandatory configs:
clusterctl config cluster capi-quickstart \
  --kubernetes-version v1.18.16 \
  --control-plane-machine-count=3 \
  --worker-machine-count=3 > capi-quickstart.yaml

**The bold lines must be add manually.**
{...}
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
	kind: KubeadmControlPlane
	metadata:
	  name: capi-quickstart-control-plane
	  namespace: default
	spec:
	  infrastructureTemplate:
	    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
	    kind: OpenStackMachineTemplate
	    name: capi-quickstart-control-plane
	  kubeadmConfigSpec:
	    clusterConfiguration:
	      apiServer:
	        extraArgs:
	          cloud-config: /etc/kubernetes/cloud.conf
	          cloud-provider: openstack
	       **service-account-issuer: https://kubernetes.default.svc.cluster.local
	          service-account-key-file: /etc/kubernetes/pki/sa.pub
	          service-account-signing-key-file: /etc/kubernetes/pki/sa.key**
{...}

**Comment by sbueringer** [comment]
@belomx Which kubeadm version is installed on your OS image?

**Comment by belomx** [comment]
Hi @sbueringer , It's the v1.17.3.

**Comment by sbueringer** [comment]
Can you try with kubeadm v1.18.*?

**Comment by belomx** [comment]
Sure, I would be very happy if you could share a link where I can download a image with  kubeadm v1.18.* :)

**Comment by sbueringer** [comment]
There are currently no officially maintained/published images for CAPO. I can only refer you to image-builder: https://image-builder.sigs.k8s.io/capi/providers/openstack.html
So you have to build the image yourself.

Other cloud providers are publishing images with the correct combination of kubeadm/kubelet/... directly into the cloud, but there is no such thing for CAPO.


The problem is that the alternative would be to somehow handle differences between kubeadm and Kubernetes versions in clusterct,. although clusterctl has no idea which kubeadm version is installed in the OS image. I think they won't accept PRs for a handling like this in https://github.com/kubernetes-sigs/cluster-api. clusterctl is not part of CAPO, but feel free to discuss this requirement with the main project.

**Comment by jichenjc** [comment]
Yes, I think it's better to open cluster-api questions and may link here
